<a href="https://colab.research.google.com/github/anvishah1/Pytorch-Learning/blob/main/pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing the libraries

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


Tensors:

In [3]:
#scaler-tensor
scaler=torch.tensor(7)
scaler
scaler.ndim # returns the dimension

0

In [4]:
#vector- tensor
vector = torch.tensor([9,7])
vector
vector.ndim

1

In [5]:
vector.shape

torch.Size([2])

In [6]:
vector[0]

tensor(9)

In [7]:
#Matrix:
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [8]:
MATRIX.ndim # how many dimesions to it think of it as a cube

2

In [9]:
MATRIX.shape#

torch.Size([2, 2])

In [10]:
#Tensor:
TENSOR = torch.tensor([[[1,2,4],[2,3,4],[4,5,6]]])
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 4],
         [4, 5, 6]]])

In [11]:
TENSOR.shape # one big cube - each cube has faces - each face has elements

torch.Size([1, 3, 3])

RANDOM TENSORS - random tensors are imp bcz all neural netowrks start w random input(weights)

In [12]:
## random tensors - size(3,4)
random_tensor = torch.rand(3,224,224)
random_tensor.shape, random_tensor.ndim

(torch.Size([3, 224, 224]), 3)

diff tensors

In [13]:
#torch range
one_to_thousand=torch.arange(start=0,end=1001, step =10)
one_to_thousand

tensor([   0,   10,   20,   30,   40,   50,   60,   70,   80,   90,  100,  110,
         120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,  230,
         240,  250,  260,  270,  280,  290,  300,  310,  320,  330,  340,  350,
         360,  370,  380,  390,  400,  410,  420,  430,  440,  450,  460,  470,
         480,  490,  500,  510,  520,  530,  540,  550,  560,  570,  580,  590,
         600,  610,  620,  630,  640,  650,  660,  670,  680,  690,  700,  710,
         720,  730,  740,  750,  760,  770,  780,  790,  800,  810,  820,  830,
         840,  850,  860,  870,  880,  890,  900,  910,  920,  930,  940,  950,
         960,  970,  980,  990, 1000])

In [14]:
# creating tensors like i.e having the exact shape as some other tnesor
hundred_zeros = torch.zeros_like(one_to_thousand)
hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0])

# to get informtion from Tensors - usally where the problem will arise while using tensors:


*   tensor not the right datatype -- use tensor.dtype
*   tensor not the right shape -- use tensor.shape
*   tensor not on the right device i.e(cpu,gpu) -- use tensor.device




In [15]:
# create a tensor
some_tensor=torch.rand([3,2])
some_tensor

tensor([[0.6179, 0.2817],
        [0.3727, 0.3306],
        [0.9323, 0.6204]])

In [16]:
# finding out information about the tensor -- attributes
print(f"the datatype of the tensor: {some_tensor.dtype}")
print(f"shape of the tensor: {some_tensor.shape}")
print(f"Device of the tensor: {some_tensor.device}")

the datatype of the tensor: torch.float32
shape of the tensor: torch.Size([3, 2])
Device of the tensor: cpu


In [17]:
# to change the dtype:

some_tensor=some_tensor.type(torch.float16)
print(some_tensor)

tensor([[0.6177, 0.2817],
        [0.3728, 0.3306],
        [0.9321, 0.6206]], dtype=torch.float16)


tensor operations:


1.   addition
2.   Subtraction
3. Multiplication - element wise
4. Division
5. matrix Multiplication



In [20]:
## manipulating tensor - tensor operations
#add
tensor = torch.tensor([1,2,3])
tensor + 10 ## this wont save the tensor unless you assign this op to another tensor

tensor([1, 2, 3])

In [25]:
# subtract
print(f"subtraction results in {tensor -10}")
#mul
print(f"multiplication results in {tensor * 10}")

subtraction results in tensor([-9, -8, -7])
multiplication results in tensor([10, 20, 30])


In [26]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [33]:
# transpose:
tensor=torch.tensor([[1,2,3],[4,5,6]])
print(tensor.shape)
print(f"post transpose: {tensor.T.shape}")

torch.Size([2, 3])
post transpose: torch.Size([3, 2])


TENSOR AGGREGATION
min,max,mean,sum

In [38]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
#find min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [41]:
#find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [44]:
#find mean - mean takes dtype as float cant use the int that we get when we do arange
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [47]:
#sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

In [48]:
#to find the index at which the min and max value occur:
print(x.argmin())
print(x.argmax())

tensor(0)
tensor(9)


RESHAPING, stacking, squeezing and unsqueezing(efficentnet?)

reshaping: to reshape the tensor
view: return the view of an input tesnro of certain shape but keep the same memory as the og tensor
stacking: stack diff tensors together
squeeze: removes all '1' dimesions from a tensor
unsqueeze : add a '1' dimension to a target tensor
permute: return a view of the input with dimensions permuted(swapped) a certain way

In [70]:
# reshaping the tensor:

x=torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [59]:
x_reshaped=x.reshape(2,5)
x_reshaped , x_reshaped.shape # can only reshape by adding dimensions so that all the elements are still there i.e the product of the dimensions should always be the same

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [62]:
# change the view:
z=x.view(3,3)
z,z.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [67]:
z[:, 0]=3 #### : means all rows 0: the index position in each row i.e that clm changes the value to 3
x, x.shape # the view and the actual tensor share memory so any change to the view will result in change to the tensor

(tensor([3, 2, 3, 3, 5, 3, 3, 8, 3]), torch.Size([9]))

In [72]:
# stacking
x_stacked = torch.stack([x,x,x],dim=1) #hstack -> dim =0 stack the entire tensor on top of one another. vstack -> dim =1 each matching element combined and put in one row
x_stacked

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [ ]:
#squeezing